// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Seller } from './seller';

export interface BusinessBase {
    id: string;
    business_id: string;
    business_type: string;
    business_description: string;
    created_at: string;
    updated_at: string;
}

export interface Business extends BusinessBase {
    seller?: Seller;
}

export type CreateBusinessPayload = Omit<BusinessBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateBusinessPayload = Partial<CreateBusinessPayload>;
