// This file is auto-generated by eloquent-typegen. Do not edit manually.

export interface CategoryBase {
    category_id: string;
    category_name: string;
    created_at: string;
    updated_at: string;
}

export interface Category extends CategoryBase {
}

export type CreateCategoryPayload = Omit<CategoryBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateCategoryPayload = Partial<CreateCategoryPayload>;
