// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Product } from './product';
import type { Message } from './message';

export interface ConversationBase {
    id: number;
    last_message_at?: Nullable<string>;
    buyer_id: string;
    seller_id: string;
    product_id: string;
    last_message?: Nullable<string>;
    unread_count_buyer: number;
    unread_count_seller: number;
    created_at: string;
    updated_at: string;
}

export interface Conversation extends ConversationBase {
    buyer?: User;
    seller?: User;
    product?: Product;
    messages?: Message[];
}

export type CreateConversationPayload = Omit<ConversationBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateConversationPayload = Partial<CreateConversationPayload>;
