// This file is auto-generated by eloquent-typegen. Do not edit manually.

export interface DatabaseNotificationBase {
    data: Record<string, unknown>;
    read_at: string;
    created_at: string;
    updated_at: string;
}

export interface DatabaseNotification extends DatabaseNotificationBase {
    notifiable?: unknown;
}

export type CreateDatabaseNotificationPayload = Omit<DatabaseNotificationBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateDatabaseNotificationPayload = Partial<CreateDatabaseNotificationPayload>;
