// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Conversation } from './conversation';
import type { User } from './user';
import type { Seller } from './seller';

export interface MessageBase {
    id: number;
    conversation_id: number;
    sender_id: string;
    sender_type: string;
    message: string;
    read: boolean;
    created_at: string;
    updated_at: string;
}

export interface Message extends MessageBase {
    conversation?: Conversation;
    user?: User;
    seller?: User;
    sender?: Seller;
}

export type CreateMessagePayload = Omit<MessageBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateMessagePayload = Partial<CreateMessagePayload>;
