// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Seller } from './seller';
import type { OrderItem } from './order-item';
import type { SellerEarning } from './seller-earning';

export interface OrderBase {
    order_id: string;
    payment_intent_id: string;
    amount: number;
    currency: string;
    payment_method: string;
    payment_status: string;
    order_status: string;
    user_id: string;
    seller_id: string;
    notes?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface Order extends OrderBase {
    user?: User;
    seller?: Seller;
    orderItems?: OrderItem[];
    sellerEarning?: SellerEarning[];
}

export type CreateOrderPayload = Omit<OrderBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateOrderPayload = Partial<CreateOrderPayload>;
