// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Order } from './order';
import type { Product } from './product';
import type { ProductImage } from './product-image';

export interface OrderItemBase {
    id: number;
    selected_variant?: Nullable<Record<string, unknown>>;
    price: number;
    order_id: string;
    product_id: string;
    quantity: number;
    created_at: string;
    updated_at: string;
}

export interface OrderItem extends OrderItemBase {
    order?: Order;
    product?: Product;
    productImage?: ProductImage;
}

export type CreateOrderItemPayload = Omit<OrderItemBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateOrderItemPayload = Partial<CreateOrderItemPayload>;
