// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Product } from './product';

export interface ProductImageBase {
    id: number;
    product_id: string;
    image_path: string;
    created_at: string;
    updated_at: string;
}

export interface ProductImage extends ProductImageBase {
    product?: Product;
}

export type CreateProductImagePayload = Omit<ProductImageBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateProductImagePayload = Partial<CreateProductImagePayload>;
