// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Product } from './product';

export interface ProductIncludeItemBase {
    item_id: string;
    product_id: string;
    item_name: string;
    created_at: string;
    updated_at: string;
}

export interface ProductIncludeItem extends ProductIncludeItemBase {
    product?: Product;
}

export type CreateProductIncludeItemPayload = Omit<ProductIncludeItemBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateProductIncludeItemPayload = Partial<CreateProductIncludeItemPayload>;
