// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Seller } from './seller';
import type { Category } from './category';
import type { OrderItem } from './order-item';
import type { Wishlist } from './wishlist';
import type { ProductFeature } from './product-feature';
import type { ProductIncludeItem } from './product-include-item';
import type { ProductImage } from './product-image';
import type { ProductVideo } from './product-video';
import type { Rating } from './rating';
import type { ProductEmbeddings } from './product-embeddings';
import type { ProductVariant } from './product-variant';

export interface ProductBase {
    product_id: string;
    product_name: string;
    product_description: string;
    product_price: number;
    product_quantity: number;
    product_status: string;
    product_condition: string;
    product_brand: unknown;
    product_material: unknown;
    product_manufacturer: unknown;
    product_weight: unknown;
    featured: boolean;
    total_ratings: number;
    seller_id: string;
    category_id: string;
    blocked_at?: Nullable<string>;
    block_reason?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface Product extends ProductBase {
    seller?: Seller;
    category?: Category;
    orderItems?: OrderItem[];
    wishlists?: Wishlist[];
    productFeature?: ProductFeature[];
    productIncludeItem?: ProductIncludeItem[];
    productImage?: ProductImage[];
    productVideo?: ProductVideo[];
    ratings?: Rating[];
    productEmbeddings?: ProductEmbeddings[];
    productVariant?: ProductVariant[];
}

export type CreateProductPayload = Omit<ProductBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateProductPayload = Partial<CreateProductPayload>;
