// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Product } from './product';

export interface ProductVariantBase {
    variant_id: string;
    product_id: string;
    variant_combination: Record<string, unknown>;
    variant_key: string;
    quantity: number;
    price: number;
    created_at: string;
    updated_at: string;
}

export interface ProductVariant extends ProductVariantBase {
    product?: Product;
}

export type CreateProductVariantPayload = Omit<ProductVariantBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateProductVariantPayload = Partial<CreateProductVariantPayload>;
