// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Product } from './product';

export interface ProductFeatureBase {
    feature_id: string;
    product_id: string;
    feature_text: string;
    created_at: string;
    updated_at: string;
}

export interface ProductFeature extends ProductFeatureBase {
    product?: Product;
}

export type CreateProductFeaturePayload = Omit<ProductFeatureBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateProductFeaturePayload = Partial<CreateProductFeaturePayload>;
