// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Product } from './product';

export interface ProductVideoBase {
    id: number;
    product_id: string;
    video_path: string;
    created_at: string;
    updated_at: string;
}

export interface ProductVideo extends ProductVideoBase {
    product?: Product;
}

export type CreateProductVideoPayload = Omit<ProductVideoBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateProductVideoPayload = Partial<CreateProductVideoPayload>;
