// This file is auto-generated by eloquent-typegen. Do not edit manually.

export interface ProductPromotionBase {
    id: number;
    promotion_id: unknown;
    product_id: unknown;
    created_at: string;
    updated_at: string;
}

export interface ProductPromotion extends ProductPromotionBase {
}

export type CreateProductPromotionPayload = Omit<ProductPromotionBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateProductPromotionPayload = Partial<CreateProductPromotionPayload>;
