// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Product } from './product';

export interface ProductEmbeddingsBase {
    id: number;
    product_id: string;
    name: string;
    embedding: Record<string, unknown>;
    created_at: string;
    updated_at: string;
}

export interface ProductEmbeddings extends ProductEmbeddingsBase {
    product?: Product;
}

export type CreateProductEmbeddingsPayload = Omit<ProductEmbeddingsBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateProductEmbeddingsPayload = Partial<CreateProductEmbeddingsPayload>;
