// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Product } from './product';

export interface RatingBase {
    id: number;
    user_id: string;
    product_id: string;
    rating: number;
    comment?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface Rating extends RatingBase {
    user?: User;
    product?: Product;
}

export type CreateRatingPayload = Omit<RatingBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateRatingPayload = Partial<CreateRatingPayload>;
