// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { User } from './user';

export interface RoleBase {
    role_id: string;
    role_name: string;
    created_at: string;
    updated_at: string;
}

export interface Role extends RoleBase {
    user?: User[];
}

export type CreateRolePayload = Omit<RoleBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateRolePayload = Partial<CreateRolePayload>;
