// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { User } from './user';
import type { SellerStore } from './seller-store';
import type { Product } from './product';
import type { Order } from './order';
import type { Conversation } from './conversation';

export interface SellerBase {
    seller_id: string;
    seller_name: string;
    seller_email: string;
    seller_phone: string;
    store_id: string;
    business_id: string;
    is_verified: boolean;
    created_at: string;
    updated_at: string;
}

export interface Seller extends SellerBase {
    user?: User;
    sellerStore?: SellerStore;
    product?: Product[];
    order?: Order[];
    conversations?: Conversation[];
}

export type CreateSellerPayload = Omit<SellerBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateSellerPayload = Partial<CreateSellerPayload>;
