// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Seller } from './seller';
import type { Order } from './order';

export interface SellerEarningBase {
    id: number;
    seller_id: string;
    order_id: string;
    amount: number;
    commission_rate: number;
    commission_deducted: number;
    payout_amount: number;
    status: string;
    processed_at?: Nullable<string>;
    paid_at?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface SellerEarning extends SellerEarningBase {
    seller?: Seller;
    order?: Order;
}

export type CreateSellerEarningPayload = Omit<SellerEarningBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateSellerEarningPayload = Partial<CreateSellerEarningPayload>;
