// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Business } from './business';

export interface SellerRegistrationBase {
    registration_id: string;
    name: string;
    email: string;
    phone_number: string;
    store_name: string;
    store_description: string;
    store_address: string;
    store_city: string;
    store_state: string;
    business_id: string;
    verification_type: string;
    verification_image: string;
    status: string;
    created_at: string;
    updated_at: string;
}

export interface SellerRegistration extends SellerRegistrationBase {
    business?: Business;
}

export type CreateSellerRegistrationPayload = Omit<SellerRegistrationBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateSellerRegistrationPayload = Partial<CreateSellerRegistrationPayload>;
