// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Seller } from './seller';

export interface SellerStoreBase {
    store_id: string;
    store_name: string;
    store_description: string;
    store_address: string;
    store_phone: string;
    store_image: string;
    created_at: string;
    updated_at: string;
}

export interface SellerStore extends SellerStoreBase {
    seller?: Seller[];
}

export type CreateSellerStorePayload = Omit<SellerStoreBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateSellerStorePayload = Partial<CreateSellerStorePayload>;
