// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Role } from './role';
import type { Seller } from './seller';
import type { Order } from './order';
import type { Product } from './product';
import type { DatabaseNotification } from './database-notification';

export interface UserBase {
    email_verified_at?: Nullable<string>;
    user_id: string;
    name: string;
    email: string;
    role_id: string;
    seller_id: string;
    status: string;
    last_login_at?: Nullable<string>;
    phone?: Nullable<string>;
    address?: Nullable<string>;
    city?: Nullable<string>;
    zip_code?: Nullable<string>;
    profile_image?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface User extends UserBase {
    role?: Role;
    seller?: Seller;
    order?: Order;
    product?: Product;
    notifications?: DatabaseNotification[];
    readNotifications?: DatabaseNotification[];
    unreadNotifications?: DatabaseNotification[];
}

export type CreateUserPayload = Omit<UserBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateUserPayload = Partial<CreateUserPayload>;
