// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Product } from './product';
import type { ProductImage } from './product-image';
import type { ProductVariant } from './product-variant';

export interface WishlistBase {
    id: number;
    user_id: string;
    product_id: string;
    selected_options: unknown;
    selected_quantity: number;
    selected_variant?: Nullable<Record<string, unknown>>;
    created_at: string;
    updated_at: string;
}

export interface Wishlist extends WishlistBase {
    user?: User;
    product?: Product;
    productImage?: ProductImage;
    productVariant?: ProductVariant[];
}

export type CreateWishlistPayload = Omit<WishlistBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateWishlistPayload = Partial<CreateWishlistPayload>;
